name: fn_compose
description: A typed way to compose functions in dart
version: 0.0.3
homepage: https://github.com/twistedinferno/fn_compose
author: twistedinferno <gu64rk@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dev_dependencies:
  test: ^1.0.0 